# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='language_id.proto',
  package='zemberek.langid',
  syntax='proto3',
  serialized_options=_b('\n\016zemberek.protoP\001'),
  serialized_pb=_b('\n\x11language_id.proto\x12\x0fzemberek.langid\":\n\x11LanguageIdRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\x16\n\x0emaxSampleCount\x18\x02 \x01(\x05\"$\n\x12LanguageIdResponse\x12\x0e\n\x06langId\x18\x01 \x01(\t2\xbd\x01\n\x11LanguageIdService\x12Q\n\x06\x44\x65tect\x12\".zemberek.langid.LanguageIdRequest\x1a#.zemberek.langid.LanguageIdResponse\x12U\n\nDetectFast\x12\".zemberek.langid.LanguageIdRequest\x1a#.zemberek.langid.LanguageIdResponseB\x12\n\x0ezemberek.protoP\x01\x62\x06proto3')
)




_LANGUAGEIDREQUEST = _descriptor.Descriptor(
  name='LanguageIdRequest',
  full_name='zemberek.langid.LanguageIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='zemberek.langid.LanguageIdRequest.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxSampleCount', full_name='zemberek.langid.LanguageIdRequest.maxSampleCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=96,
)


_LANGUAGEIDRESPONSE = _descriptor.Descriptor(
  name='LanguageIdResponse',
  full_name='zemberek.langid.LanguageIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='langId', full_name='zemberek.langid.LanguageIdResponse.langId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['LanguageIdRequest'] = _LANGUAGEIDREQUEST
DESCRIPTOR.message_types_by_name['LanguageIdResponse'] = _LANGUAGEIDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LanguageIdRequest = _reflection.GeneratedProtocolMessageType('LanguageIdRequest', (_message.Message,), dict(
  DESCRIPTOR = _LANGUAGEIDREQUEST,
  __module__ = 'language_id_pb2'
  # @@protoc_insertion_point(class_scope:zemberek.langid.LanguageIdRequest)
  ))
_sym_db.RegisterMessage(LanguageIdRequest)

LanguageIdResponse = _reflection.GeneratedProtocolMessageType('LanguageIdResponse', (_message.Message,), dict(
  DESCRIPTOR = _LANGUAGEIDRESPONSE,
  __module__ = 'language_id_pb2'
  # @@protoc_insertion_point(class_scope:zemberek.langid.LanguageIdResponse)
  ))
_sym_db.RegisterMessage(LanguageIdResponse)


DESCRIPTOR._options = None

_LANGUAGEIDSERVICE = _descriptor.ServiceDescriptor(
  name='LanguageIdService',
  full_name='zemberek.langid.LanguageIdService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=137,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='zemberek.langid.LanguageIdService.Detect',
    index=0,
    containing_service=None,
    input_type=_LANGUAGEIDREQUEST,
    output_type=_LANGUAGEIDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DetectFast',
    full_name='zemberek.langid.LanguageIdService.DetectFast',
    index=1,
    containing_service=None,
    input_type=_LANGUAGEIDREQUEST,
    output_type=_LANGUAGEIDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LANGUAGEIDSERVICE)

DESCRIPTOR.services_by_name['LanguageIdService'] = _LANGUAGEIDSERVICE

# @@protoc_insertion_point(module_scope)
