# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import normalization_pb2 as normalization__pb2


class NormalizationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Normalize = channel.unary_unary(
        '/zemberek.normalization.NormalizationService/Normalize',
        request_serializer=normalization__pb2.NormalizationRequest.SerializeToString,
        response_deserializer=normalization__pb2.NormalizationResponse.FromString,
        )


class NormalizationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Normalize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NormalizationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Normalize': grpc.unary_unary_rpc_method_handler(
          servicer.Normalize,
          request_deserializer=normalization__pb2.NormalizationRequest.FromString,
          response_serializer=normalization__pb2.NormalizationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'zemberek.normalization.NormalizationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
