<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language_id.proto

namespace Zemberek\Langid;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class DetectRequest extends \Google\Protobuf\Internal\Message
{
    private $input = '';
    private $maxSampleCount = 0;

    public function getInput()
    {
        return $this->input;
    }

    public function setInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->input = $var;
    }

    public function getMaxSampleCount()
    {
        return $this->maxSampleCount;
    }

    public function setMaxSampleCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxSampleCount = $var;
    }

}

class DetectResponse extends \Google\Protobuf\Internal\Message
{
    private $langId = '';

    public function getLangId()
    {
        return $this->langId;
    }

    public function setLangId($var)
    {
        GPBUtil::checkString($var, True);
        $this->langId = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aca020a116c616e67756167655f69642e70726f746f120f7a656d626572" .
    "656b2e6c616e67696422360a0d44657465637452657175657374120d0a05" .
    "696e70757418012001280912160a0e6d617853616d706c65436f756e7418" .
    "022001280522200a0e446574656374526573706f6e7365120e0a066c616e" .
    "67496418012001280932ad010a114c616e67756167654964536572766963" .
    "6512490a06446574656374121e2e7a656d626572656b2e6c616e6769642e" .
    "446574656374526571756573741a1f2e7a656d626572656b2e6c616e6769" .
    "642e446574656374526573706f6e7365124d0a0a44657465637446617374" .
    "121e2e7a656d626572656b2e6c616e6769642e4465746563745265717565" .
    "73741a1f2e7a656d626572656b2e6c616e6769642e446574656374526573" .
    "706f6e736542120a0e7a656d626572656b2e70726f746f5001620670726f" .
    "746f33"
));

