<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: normalization.proto

namespace Zemberek\Normalization;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class NormalizationRequest extends \Google\Protobuf\Internal\Message
{
    private $input = '';

    public function getInput()
    {
        return $this->input;
    }

    public function setInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->input = $var;
    }

}

class NormalizationResponse extends \Google\Protobuf\Internal\Message
{
    private $normalized_input = '';

    public function getNormalizedInput()
    {
        return $this->normalized_input;
    }

    public function setNormalizedInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->normalized_input = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aa6020a136e6f726d616c697a6174696f6e2e70726f746f12167a656d62" .
    "6572656b2e6e6f726d616c697a6174696f6e22250a144e6f726d616c697a" .
    "6174696f6e52657175657374120d0a05696e70757418012001280922310a" .
    "154e6f726d616c697a6174696f6e526573706f6e736512180a106e6f726d" .
    "616c697a65645f696e7075741802200128093280010a144e6f726d616c69" .
    "7a6174696f6e5365727669636512680a094e6f726d616c697a65122c2e7a" .
    "656d626572656b2e6e6f726d616c697a6174696f6e2e4e6f726d616c697a" .
    "6174696f6e526571756573741a2d2e7a656d626572656b2e6e6f726d616c" .
    "697a6174696f6e2e4e6f726d616c697a6174696f6e526573706f6e736542" .
    "120a0e7a656d626572656b2e70726f746f5001620670726f746f33"
));

