<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: preprocess.proto

namespace Zemberek\Preprocessor;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class TokenizationRequest extends \Google\Protobuf\Internal\Message
{
    private $input = '';
    private $includeTokenBoundaries = false;

    public function getInput()
    {
        return $this->input;
    }

    public function setInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->input = $var;
    }

    public function getIncludeTokenBoundaries()
    {
        return $this->includeTokenBoundaries;
    }

    public function setIncludeTokenBoundaries($var)
    {
        GPBUtil::checkBool($var);
        $this->includeTokenBoundaries = $var;
    }

}

class Token extends \Google\Protobuf\Internal\Message
{
    private $token = '';
    private $type = '';
    private $start = 0;
    private $end = 0;

    public function getToken()
    {
        return $this->token;
    }

    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;
    }

    public function getStart()
    {
        return $this->start;
    }

    public function setStart($var)
    {
        GPBUtil::checkInt32($var);
        $this->start = $var;
    }

    public function getEnd()
    {
        return $this->end;
    }

    public function setEnd($var)
    {
        GPBUtil::checkInt32($var);
        $this->end = $var;
    }

}

class TokenizationResponse extends \Google\Protobuf\Internal\Message
{
    private $tokens;

    public function getTokens()
    {
        return $this->tokens;
    }

    public function setTokens(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Zemberek\Preprocessor\Token::class);
        $this->tokens = $var;
    }

}

class SentenceExtractionRequest extends \Google\Protobuf\Internal\Message
{
    private $document = '';

    public function getDocument()
    {
        return $this->document;
    }

    public function setDocument($var)
    {
        GPBUtil::checkString($var, True);
        $this->document = $var;
    }

}

class SentenceExtractionResponse extends \Google\Protobuf\Internal\Message
{
    private $sentences;

    public function getSentences()
    {
        return $this->sentences;
    }

    public function setSentences(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->sentences = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aea040a1070726570726f636573732e70726f746f12157a656d62657265" .
    "6b2e70726570726f636573736f7222440a13546f6b656e697a6174696f6e" .
    "52657175657374120d0a05696e707574180120012809121e0a16696e636c" .
    "756465546f6b656e426f756e64617269657318022001280822400a05546f" .
    "6b656e120d0a05746f6b656e180120012809120c0a047479706518022001" .
    "2809120d0a057374617274180320012805120b0a03656e64180420012805" .
    "22440a14546f6b656e697a6174696f6e526573706f6e7365122c0a06746f" .
    "6b656e7318012003280b321c2e7a656d626572656b2e70726570726f6365" .
    "73736f722e546f6b656e222d0a1953656e74656e63654578747261637469" .
    "6f6e5265717565737412100a08646f63756d656e74180120012809222f0a" .
    "1a53656e74656e636545787472616374696f6e526573706f6e736512110a" .
    "0973656e74656e63657318012003280932f4010a1450726570726f636573" .
    "73696e675365727669636512630a08546f6b656e697a65122a2e7a656d62" .
    "6572656b2e70726570726f636573736f722e546f6b656e697a6174696f6e" .
    "526571756573741a2b2e7a656d626572656b2e70726570726f636573736f" .
    "722e546f6b656e697a6174696f6e526573706f6e736512770a1045787472" .
    "61637453656e74656e63657312302e7a656d626572656b2e70726570726f" .
    "636573736f722e53656e74656e636545787472616374696f6e5265717565" .
    "73741a312e7a656d626572656b2e70726570726f636573736f722e53656e" .
    "74656e636545787472616374696f6e526573706f6e736542120a0e7a656d" .
    "626572656b2e70726f746f5001620670726f746f33"
));

