<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_analysis.proto

namespace Zemberek\Simple_analysis;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class SentenceRequest extends \Google\Protobuf\Internal\Message
{
    private $input = '';

    public function getInput()
    {
        return $this->input;
    }

    public function setInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->input = $var;
    }

}

class WordRequest extends \Google\Protobuf\Internal\Message
{
    private $input = '';

    public function getInput()
    {
        return $this->input;
    }

    public function setInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->input = $var;
    }

}

class DictionaryItem_P extends \Google\Protobuf\Internal\Message
{
    private $lemma = '';
    private $pos = '';
    private $pos2 = '';

    public function getLemma()
    {
        return $this->lemma;
    }

    public function setLemma($var)
    {
        GPBUtil::checkString($var, True);
        $this->lemma = $var;
    }

    public function getPos()
    {
        return $this->pos;
    }

    public function setPos($var)
    {
        GPBUtil::checkString($var, True);
        $this->pos = $var;
    }

    public function getPos2()
    {
        return $this->pos2;
    }

    public function setPos2($var)
    {
        GPBUtil::checkString($var, True);
        $this->pos2 = $var;
    }

}

class SingleAnalysis_P extends \Google\Protobuf\Internal\Message
{
    private $pos = '';
    private $dictionaryItem = null;
    private $analysis = '';
    private $informal = false;
    private $runtime = false;
    private $lemmas;

    public function getPos()
    {
        return $this->pos;
    }

    public function setPos($var)
    {
        GPBUtil::checkString($var, True);
        $this->pos = $var;
    }

    public function getDictionaryItem()
    {
        return $this->dictionaryItem;
    }

    public function setDictionaryItem(&$var)
    {
        GPBUtil::checkMessage($var, \Zemberek\Simple_analysis\DictionaryItem_P::class);
        $this->dictionaryItem = $var;
    }

    public function getAnalysis()
    {
        return $this->analysis;
    }

    public function setAnalysis($var)
    {
        GPBUtil::checkString($var, True);
        $this->analysis = $var;
    }

    public function getInformal()
    {
        return $this->informal;
    }

    public function setInformal($var)
    {
        GPBUtil::checkBool($var);
        $this->informal = $var;
    }

    public function getRuntime()
    {
        return $this->runtime;
    }

    public function setRuntime($var)
    {
        GPBUtil::checkBool($var);
        $this->runtime = $var;
    }

    public function getLemmas()
    {
        return $this->lemmas;
    }

    public function setLemmas(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->lemmas = $var;
    }

}

class WordAnalysis_P extends \Google\Protobuf\Internal\Message
{
    private $input = '';
    private $analyses;

    public function getInput()
    {
        return $this->input;
    }

    public function setInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->input = $var;
    }

    public function getAnalyses()
    {
        return $this->analyses;
    }

    public function setAnalyses(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Zemberek\Simple_analysis\SingleAnalysis_P::class);
        $this->analyses = $var;
    }

}

class SentenceWordAnalysis_P extends \Google\Protobuf\Internal\Message
{
    private $token = '';
    private $best = null;
    private $all = null;

    public function getToken()
    {
        return $this->token;
    }

    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;
    }

    public function getBest()
    {
        return $this->best;
    }

    public function setBest(&$var)
    {
        GPBUtil::checkMessage($var, \Zemberek\Simple_analysis\SingleAnalysis_P::class);
        $this->best = $var;
    }

    public function getAll()
    {
        return $this->all;
    }

    public function setAll(&$var)
    {
        GPBUtil::checkMessage($var, \Zemberek\Simple_analysis\WordAnalysis_P::class);
        $this->all = $var;
    }

}

class SentenceAnalysis_P extends \Google\Protobuf\Internal\Message
{
    private $input = '';
    private $results;

    public function getInput()
    {
        return $this->input;
    }

    public function setInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->input = $var;
    }

    public function getResults()
    {
        return $this->results;
    }

    public function setResults(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Zemberek\Simple_analysis\SentenceWordAnalysis_P::class);
        $this->results = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ace070a1573696d706c655f616e616c797369732e70726f746f12187a65" .
    "6d626572656b2e73696d706c655f616e616c7973697322200a0f53656e74" .
    "656e636552657175657374120d0a05696e707574180120012809221c0a0b" .
    "576f726452657175657374120d0a05696e707574180120012809223c0a10" .
    "44696374696f6e6172794974656d5f50120d0a056c656d6d611801200128" .
    "09120b0a03706f73180220012809120c0a04706f733218032001280922a8" .
    "010a1053696e676c65416e616c797369735f50120b0a03706f7318012001" .
    "280912420a0e64696374696f6e6172794974656d18022001280b322a2e7a" .
    "656d626572656b2e73696d706c655f616e616c797369732e44696374696f" .
    "6e6172794974656d5f5012100a08616e616c797369731803200128091210" .
    "0a08696e666f726d616c180420012808120f0a0772756e74696d65180520" .
    "012808120e0a066c656d6d6173180620032809225d0a0e576f7264416e61" .
    "6c797369735f50120d0a05696e707574180120012809123c0a08616e616c" .
    "7973657318022003280b322a2e7a656d626572656b2e73696d706c655f61" .
    "6e616c797369732e53696e676c65416e616c797369735f502298010a1653" .
    "656e74656e6365576f7264416e616c797369735f50120d0a05746f6b656e" .
    "18012001280912380a046265737418022001280b322a2e7a656d62657265" .
    "6b2e73696d706c655f616e616c797369732e53696e676c65416e616c7973" .
    "69735f5012350a03616c6c18032001280b32282e7a656d626572656b2e73" .
    "696d706c655f616e616c797369732e576f7264416e616c797369735f5022" .
    "660a1253656e74656e6365416e616c797369735f50120d0a05696e707574" .
    "18012001280912410a07726573756c747318022003280b32302e7a656d62" .
    "6572656b2e73696d706c655f616e616c797369732e53656e74656e636557" .
    "6f7264416e616c797369735f5032e3010a1553696d706c65416e616c7973" .
    "697353657276696365126a0a0f416e616c797a6553656e74656e63651229" .
    "2e7a656d626572656b2e73696d706c655f616e616c797369732e53656e74" .
    "656e6365526571756573741a2c2e7a656d626572656b2e73696d706c655f" .
    "616e616c797369732e53656e74656e6365416e616c797369735f50125e0a" .
    "0b416e616c797a65576f726412252e7a656d626572656b2e73696d706c65" .
    "5f616e616c797369732e576f7264526571756573741a282e7a656d626572" .
    "656b2e73696d706c655f616e616c797369732e576f7264416e616c797369" .
    "735f5042220a1e7a656d626572656b2e70726f746f2e73696d706c655f61" .
    "6e616c797369735001620670726f746f33"
));

